name: Prepare Cordova Project for APK

on:
  push:
    paths:
      - 'www/**'
      - '.github/workflows/android-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          cordova create tictac com.example.tictactoe "Tic Tac Toe Multimodo"
          rm -rf tictac/www
          cp -r www tictac/www
          cd tictac
          cordova platform add android

      - name: Zip the Cordova project
        run: zip -r tictac-project.zip tictac

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: cordova-project
          path: tictac-project.zip
