name: Build Android APK

on:
  push:
    paths:
      - 'www/**'
      - '.github/workflows/android-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Prepare project
        run: |
          cordova create tictac com.example.tictactoe "Tic Tac Toe Multimodo"
          cd tictac
          cp -r ../www/* www/
          cordova platform add android
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: tictac/platforms/android/app/build/outputs/apk/release/app-release.apk
